// Generated by PERL program wishbone.pl. Do not edit this file.
//
// For defines see intercon.defines
//
// Generated Tue Aug 21 11:40:57 2007
//
// Wishbone masters:
//   lm32i
//   lm32d
//
// Wishbone slaves:
//   bram0
//     baseadr 0x00000000 - size 0x00001000
//   farbborg0
//     baseadr 0x80010000 - size 0x00010000
//   timer0
//     baseadr 0x80000000 - size 0x00001000
//   uart0
//     baseadr 0x80001000 - size 0x00001000
//   gpio0
//     baseadr 0x80002000 - size 0x00001000
//   sram0
//     baseadr 0xB0000000 - size 0x00040000
